env:
  exceptionPath: "classpath:exception.yml"

spring:
  profiles:
    active: server

#springdoc:
#  packages-to-scan: com.project.matchimban
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  swagger-ui:
#    path: matchimban.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    groups:
#      enabled: true
#  cache:
#    disabled: true